import type {
  CharaCardV3,
  CharaCardV3Data,
  NovelCharacterDraft,
} from './targets';

export const NOVEL_CHARACTER_EXTENSION_KEY =
  'shinewriter_novel_character_v1' as const;

const TEXT_FIELDS = [
  'role',
  'identity',
  'appearance',
  'background',
  'personality',
  'motivation',
  'conflict',
  'abilities',
  'limitations',
  'secrets',
  'speech_style',
  'behavior_habits',
  'arc',
  'initial_situation',
] as const;

const ARRAY_FIELDS = ['aliases', 'relationships', 'continuity', 'tags'] as const;

const RESERVED_FIELDS = new Set([
  'name',
  ...TEXT_FIELDS,
  ...ARRAY_FIELDS,
  'extra_fields',
  // These are legacy CCv3 protocol fields. They are intentionally not copied
  // into a new novel draft or generated by the construction contract.
  'description',
  'personality',
  'scenario',
  'first_mes',
  'mes_example',
  'system_prompt',
  'post_history_instructions',
  'alternate_greetings',
  'creator',
  'character_version',
  'spec',
  'spec_version',
  'extensions',
]);

function asString(value: unknown): string {
  if (typeof value === 'string') return value.trim();
  if (value == null) return '';
  return String(value).trim();
}

function asStringArray(value: unknown): string[] {
  if (Array.isArray(value)) return value.map(asString).filter(Boolean);
  const text = asString(value);
  return text ? [text] : [];
}

function asRecord(value: unknown): Record<string, unknown> {
  return value && typeof value === 'object' && !Array.isArray(value)
    ? (value as Record<string, unknown>)
    : {};
}

/** 读取 CCv3 envelope 或构建响应中的 data 包装层。 */
export function unwrapCharacterDraftSource(
  value: unknown,
): Record<string, unknown> {
  const record = asRecord(value);
  return asRecord(record.data) && Object.keys(asRecord(record.data)).length > 0
    ? asRecord(record.data)
    : record;
}

/**
 * 把模型返回的小说语义 JSON 归一化为稳定的中间模型。
 * 不读取/生成 CCv3 chat 字段；未知语义字段进入 extra_fields，避免在
 * 构建层静默丢失模型确实返回的补充资料。
 */
export function parseNovelCharacterDraft(value: unknown): NovelCharacterDraft {
  const source = unwrapCharacterDraftSource(value);
  const name = asString(source.name);
  if (!name) throw new Error('生成的角色档案缺少角色名称。');

  const draft: NovelCharacterDraft = { name };
  for (const field of TEXT_FIELDS) {
    const text = asString(source[field]);
    if (text) draft[field] = text;
  }
  for (const field of ARRAY_FIELDS) {
    const values = asStringArray(source[field]);
    if (values.length > 0) draft[field] = values;
  }

  const explicitExtra = asRecord(source.extra_fields);
  const unknownFields = Object.fromEntries(
    Object.entries(source).filter(([key]) => !RESERVED_FIELDS.has(key)),
  );
  const extraFields = { ...explicitExtra, ...unknownFields };
  if (Object.keys(extraFields).length > 0) draft.extra_fields = extraFields;
  return draft;
}

export function novelDraftHasCoreInfo(draft: NovelCharacterDraft): boolean {
  const hasIdentity = Boolean(
    asString(draft.role) || asString(draft.identity) || asString(draft.background),
  );
  const hasInner = Boolean(
    asString(draft.personality) ||
      asString(draft.motivation) ||
      asString(draft.conflict),
  );
  return hasIdentity && hasInner;
}

function extensionFromDraft(draft: NovelCharacterDraft): Record<string, unknown> {
  const extension: Record<string, unknown> = {
    aliases: asStringArray(draft.aliases),
    role: asString(draft.role),
    identity: asString(draft.identity),
    appearance: asString(draft.appearance),
    background: asString(draft.background),
    personality: asString(draft.personality),
    motivation: asString(draft.motivation),
    conflict: asString(draft.conflict),
    relationships: asStringArray(draft.relationships),
    abilities: asString(draft.abilities),
    limitations: asString(draft.limitations),
    secrets: asString(draft.secrets),
    speech_style: asString(draft.speech_style),
    behavior_habits: asString(draft.behavior_habits),
    arc: asString(draft.arc),
    continuity: asStringArray(draft.continuity),
    initial_situation: asString(draft.initial_situation),
    tags: asStringArray(draft.tags),
  };
  if (draft.extra_fields && Object.keys(draft.extra_fields).length > 0) {
    extension.extra_fields = draft.extra_fields;
  }
  return extension;
}

function joinSection(label: string, value: string | string[] | undefined): string {
  const values = Array.isArray(value)
    ? value.map(asString).filter(Boolean).join('\n')
    : asString(value);
  return values ? `【${label}】\n${values}` : '';
}

/** 把完整小说角色中间模型编译为通用可读的 description 文本。 */
export function novelCharacterDraftToDescription(
  draft: NovelCharacterDraft,
): string {
  return [
    joinSection('角色定位', draft.role),
    joinSection('身份与社会位置', draft.identity),
    joinSection('外貌与辨识特征', draft.appearance),
    joinSection('成长环境与关键经历', draft.background),
    joinSection('核心性格', draft.personality),
    joinSection('动机与目标', draft.motivation),
    joinSection('矛盾与弱点', draft.conflict),
    joinSection('关键关系', draft.relationships),
    joinSection('能力与资源', draft.abilities),
    joinSection('能力边界', draft.limitations),
    joinSection('秘密与认知盲区', draft.secrets),
    joinSection('语言与行为', [draft.speech_style, draft.behavior_habits].filter(Boolean) as string[]),
    joinSection('人物弧', draft.arc),
    joinSection('连续性事实', draft.continuity),
  ]
    .filter(Boolean)
    .join('\n\n');
}

/** 由小说语义中间模型确定性生成 CCv3 envelope。 */
export function novelCharacterDraftToCharaCard(
  draft: NovelCharacterDraft,
): CharaCardV3 {
  const normalized = parseNovelCharacterDraft(draft);
  const extension = extensionFromDraft(normalized);
  const data: CharaCardV3Data = {
    name: normalized.name,
    description: novelCharacterDraftToDescription(normalized),
    personality: asString(normalized.personality),
    scenario: asString(normalized.initial_situation),
    first_mes: '',
    mes_example: '',
    system_prompt: '',
    post_history_instructions: '',
    tags: asStringArray(normalized.tags),
    alternate_greetings: [],
    creator: 'ShineWriter 构建',
    character_version: '1.0',
    extensions: {
      [NOVEL_CHARACTER_EXTENSION_KEY]: extension,
    },
  };
  return { spec: 'chara_card_v3', spec_version: '3.0', data };
}

/** 从已保存的 CCv3 data 读取 ShineWriter 小说扩展。 */
export function readNovelCharacterDraft(value: unknown): NovelCharacterDraft | null {
  const data = unwrapCharacterDraftSource(value);
  const extensions = asRecord(data.extensions);
  const extension = asRecord(extensions[NOVEL_CHARACTER_EXTENSION_KEY]);
  if (Object.keys(extension).length === 0) return null;
  return parseNovelCharacterDraft({ name: data.name, ...extension });
}

export function createEmptyNovelCharacterDraft(name = ''): NovelCharacterDraft {
  return { name };
}
