package com.shinewriter.llamacpp

/**
 * llama.cpp 原生模块错误码常量。
 *
 * 跨 JNI/RN 边界的错误统一用字符串 code 标识，TS 侧（LlamaCppProvider）
 * 会拿这些 code 做条件判断，字符串值不可随意改动。
 */
object LlamaCppErrors {
    const val ENGINE_UNAVAILABLE = "ENGINE_UNAVAILABLE"
    const val UNSUPPORTED_FILE_TYPE = "UNSUPPORTED_FILE_TYPE"
    const val SOURCE_URI_UNREADABLE = "SOURCE_URI_UNREADABLE"
    const val SOURCE_FILE_EMPTY = "SOURCE_FILE_EMPTY"
    const val INSUFFICIENT_STORAGE = "INSUFFICIENT_STORAGE"
    const val INSUFFICIENT_MEMORY = "INSUFFICIENT_MEMORY"
    const val IMPORT_CANCELLED = "IMPORT_CANCELLED"
    const val IMPORT_COPY_FAILED = "IMPORT_COPY_FAILED"
    const val IMPORT_INCOMPLETE = "IMPORT_INCOMPLETE"
    const val MODEL_FILE_MISSING = "MODEL_FILE_MISSING"
    const val MODEL_FILE_OUTSIDE_ROOT = "MODEL_FILE_OUTSIDE_ROOT"
    const val MODEL_LOAD_FAILED = "MODEL_LOAD_FAILED"
    const val MODEL_CORRUPTED = "MODEL_CORRUPTED"
    const val ENGINE_NOT_READY = "ENGINE_NOT_READY"
    const val ENGINE_BUSY = "ENGINE_BUSY"
    const val GENERATION_FAILED = "GENERATION_FAILED"
    const val GENERATION_CANCELLED = "GENERATION_CANCELLED"
    const val DELETE_FAILED = "DELETE_FAILED"
    const val GGUF_HEADER_INVALID = "GGUF_HEADER_INVALID"
    const val GGUF_UNSUPPORTED_VERSION = "GGUF_UNSUPPORTED_VERSION"
}
