export interface TableManifest {
  name: string;
  columns: readonly string[];
  indexes?: readonly string[];
  backup: boolean;
  restoreOrder: number;
}

/**
 * The current schema contract used by runtime validation and backup planning.
 * Keep this list aligned with the latest fresh-install CREATE TABLE statements
 * and add a migration before changing a persisted column requirement.
 */
export const SCHEMA_MANIFEST: readonly TableManifest[] = [
  {
    name: 'projects',
    columns: ['id', 'name', 'mode', 'created_at', 'updated_at'],
    backup: true,
    restoreOrder: 10,
  },
  {
    name: 'chapters',
    columns: [
      'id',
      'project_id',
      'position',
      'title',
      'synopsis',
      'content',
      'status',
      'summary_json',
      'memory_summary',
      'memory_summary_tokens',
      'finalized_at',
      'created_at',
      'updated_at',
    ],
    backup: true,
    restoreOrder: 20,
  },
  {
    name: 'fragments',
    columns: ['id', 'project_id', 'position', 'type', 'content', 'created_at'],
    backup: true,
    restoreOrder: 30,
  },
  {
    name: 'project_story_memory',
    columns: [
      'project_id', 'schema_version', 'through_chapter_id',
      'through_chapter_position', 'memory_json', 'estimated_tokens',
      'state_fingerprint', 'last_applied_patch_id', 'status', 'source',
      'dirty_from_position', 'last_error', 'updated_at',
    ],
    indexes: ['idx_project_story_memory_status', 'idx_project_story_memory_dirty'],
    backup: true,
    restoreOrder: 35,
  },
  {
    name: 'chapter_memory_patches',
    columns: [
      'chapter_id', 'project_id', 'chapter_position', 'patch_id',
      'schema_version', 'source_fingerprint', 'base_memory_fingerprint',
      'result_memory_fingerprint', 'episodic_summary_json', 'patch_json',
      'estimated_tokens', 'status', 'last_error', 'generated_at', 'applied_at',
    ],
    indexes: [
      'idx_chapter_memory_patches_project_position',
      'idx_chapter_memory_patches_status',
    ],
    backup: true,
    restoreOrder: 36,
  },
  {
    name: 'story_memory_snapshots',
    columns: [
      'id', 'project_id', 'through_chapter_id', 'through_chapter_position',
      'memory_json', 'estimated_tokens', 'state_fingerprint', 'created_at',
    ],
    indexes: ['idx_story_memory_snapshots_project_position'],
    backup: true,
    restoreOrder: 37,
  },
  {
    name: 'project_story_memory_policy',
    columns: [
      'project_id', 'mode', 'interval_chapters', 'pending_token_soft_limit',
      'update_on_key_chapter', 'updated_at',
    ],
    backup: true,
    restoreOrder: 38,
  },
  {
    name: 'story_memory_batches',
    columns: [
      'batch_id', 'project_id', 'from_chapter_id', 'from_position',
      'through_chapter_id', 'through_position', 'schema_version',
      'source_fingerprint', 'base_state_fingerprint', 'result_state_fingerprint',
      'patch_json', 'chapter_summaries_json', 'estimated_tokens', 'status',
      'last_error', 'generated_at', 'applied_at',
    ],
    indexes: [
      'idx_story_memory_batches_project_range',
      'idx_story_memory_batches_project_through',
      'idx_story_memory_batches_status',
    ],
    backup: true,
    restoreOrder: 39,
  },
  {
    name: 'plotlines',
    columns: ['id', 'project_id', 'name', 'description', 'color'],
    backup: true,
    restoreOrder: 40,
  },
  {
    name: 'project_plotlines',
    columns: ['chapter_id', 'plotline_id'],
    backup: true,
    restoreOrder: 50,
  },
  {
    name: 'characters',
    columns: [
      'id',
      'project_id',
      'collection_id',
      'name',
      'source_type',
      'data_json',
      'max_tokens',
      'estimated_tokens',
      'created_at',
    ],
    backup: true,
    restoreOrder: 60,
  },
  {
    name: 'character_collections',
    columns: [
      'id',
      'project_id',
      'name',
      'enabled',
      'max_tokens',
      'estimated_tokens',
      'created_at',
    ],
    backup: true,
    restoreOrder: 65,
  },
  {
    name: 'worldbook_collections',
    columns: [
      'id',
      'project_id',
      'name',
      'enabled',
      'max_tokens',
      'estimated_tokens',
      'created_at',
    ],
    backup: true,
    restoreOrder: 70,
  },
  {
    name: 'worldbook_entries',
    columns: [
      'id',
      'project_id',
      'collection_id',
      'keyword_primary',
      'keyword_secondary',
      'content',
      'comment',
      'enabled',
      'constant',
      'max_tokens',
      'estimated_tokens',
      'position',
      'created_at',
    ],
    backup: true,
    restoreOrder: 80,
  },
  {
    name: 'note_collections',
    columns: [
      'id',
      'project_id',
      'name',
      'enabled',
      'max_tokens',
      'estimated_tokens',
      'created_at',
    ],
    backup: true,
    restoreOrder: 85,
  },
  {
    name: 'notes',
    columns: [
      'id',
      'project_id',
      'collection_id',
      'title',
      'content',
      'max_tokens',
      'estimated_tokens',
      'created_at',
      'updated_at',
    ],
    indexes: ['idx_notes_collection_id'],
    backup: true,
    restoreOrder: 90,
  },
  {
    name: 'presets',
    columns: [
      'id',
      'project_id',
      'name',
      'is_default',
      'system_prompt',
      'writing_style',
      'temperature',
      'top_p',
      'max_tokens',
      'extra_instructions',
    ],
    backup: true,
    restoreOrder: 100,
  },
  {
    name: 'llm_config',
    columns: [
      'id',
      'name',
      'base_url',
      'api_key',
      'model_name',
      'is_active',
      'provider_type',
      'local_model_id',
      'local_backend',
      'context_window',
      'max_output_tokens',
    ],
    backup: true,
    restoreOrder: 110,
  },
  {
    name: 'local_llm_models',
    columns: [
      'id',
      'display_name',
      'original_filename',
      'relative_path',
      'file_size',
      'sha256',
      'status',
      'backend_preference',
      'validated_backend',
      'context_length',
      'max_output_tokens',
      'load_time_ms',
      'first_token_ms',
      'tokens_per_second',
      'imported_at',
      'last_used_at',
      'last_validated_at',
      'error_code',
      'error_message',
      'prompt_template',
      'actual_backend',
    ],
    indexes: ['idx_local_llm_models_status', 'idx_local_llm_models_last_used'],
    backup: true,
    restoreOrder: 115,
  },
  {
    name: 'settings',
    columns: ['key', 'value'],
    backup: true,
    restoreOrder: 120,
  },
  {
    name: 'project_resources',
    columns: ['project_id', 'resource_type', 'resource_id', 'enabled'],
    backup: true,
    restoreOrder: 130,
  },
  {
    name: 'project_collection_settings',
    columns: ['project_id', 'resource_type', 'collection_id', 'enabled'],
    indexes: ['idx_project_collection_settings_lookup'],
    backup: true,
    restoreOrder: 135,
  },
  {
    name: 'llm_usage_logs',
    columns: [
      'id',
      'scenario',
      'input_tokens',
      'output_tokens',
      'total_tokens',
      'status',
      'error_code',
      'model_name',
      'project_id',
      'llm_config_id',
      'llm_config_name',
      'created_at',
    ],
    indexes: ['idx_llm_usage_logs_month', 'idx_llm_usage_logs_config'],
    backup: true,
    restoreOrder: 140,
  },
  {
    name: 'pipeline_tasks',
    columns: [
      'id',
      'target_type',
      'target_id',
      'status',
      'stage_results',
      'final_text',
      'error',
      'created_at',
      'updated_at',
      'resolved_at',
      'resolved_action',
    ],
    backup: true,
    restoreOrder: 150,
  },
  {
    name: 'freeform_documents',
    columns: ['project_id', 'content', 'updated_at'],
    backup: true,
    restoreOrder: 160,
  },
  {
    name: 'content_revisions',
    columns: [
      'id',
      'project_id',
      'target_type',
      'target_id',
      'title',
      'content',
      'source',
      'source_ref',
      'created_at',
    ],
    indexes: ['idx_content_revisions_target'],
    backup: true,
    restoreOrder: 170,
  },
  {
    name: 'generation_drafts',
    columns: [
      'id',
      'project_id',
      'target_type',
      'target_id',
      'content',
      'source',
      'pipeline_task_id',
      'token_count',
      'created_at',
    ],
    indexes: ['idx_generation_drafts_target'],
    backup: true,
    restoreOrder: 180,
  },
  {
    name: 'project_note_config',
    columns: [
      'project_id',
      'mode',
      'style_weights',
      'retrieval_top_k',
      'retrieval_fragment_chars',
      'enabled_note_ids',
      'updated_at',
    ],
    backup: true,
    restoreOrder: 190,
  },
  {
    name: 'note_style_profiles',
    columns: [
      'note_id',
      'profile_text',
      'profile_json',
      'analyzed_at',
      'source_hash',
    ],
    backup: true,
    restoreOrder: 200,
  },
  // Schema 19 (continuation Phase 1). Restore order is parent-first so foreign
  // keys resolve during INSERT: sources → chunks/chapters → settings. Import
  // jobs are transient runtime state and excluded from backup (Spec §9.6, §15)
  // but still listed so the schema validator recognises the tables.
  {
    name: 'continuation_sources',
    columns: [
      'id',
      'project_id',
      'version',
      'status',
      'display_name',
      'original_file_name',
      'mime_type',
      'detected_encoding',
      'file_size_bytes',
      'raw_sha256',
      'normalized_sha256',
      'normalized_char_count',
      'normalized_byte_count',
      'chapter_count',
      'parser_version',
      'normalization_version',
      'error_code',
      'error_message',
      'created_at',
      'updated_at',
      'activated_at',
    ],
    indexes: ['idx_continuation_sources_one_ready'],
    backup: true,
    restoreOrder: 210,
  },
  {
    name: 'continuation_source_text_chunks',
    columns: [
      'id',
      'source_id',
      'chunk_index',
      'char_start_offset',
      'char_end_offset',
      'content',
      'content_sha256',
    ],
    indexes: ['idx_continuation_text_chunks_range'],
    backup: true,
    restoreOrder: 220,
  },
  {
    name: 'continuation_source_chapters',
    columns: [
      'id',
      'source_id',
      'position',
      'volume_title',
      'detected_title',
      'title',
      'content_sha256',
      'char_count',
      'paragraph_count',
      'source_start_offset',
      'content_start_offset',
      'source_end_offset',
      'is_excluded',
      'exclusion_reason',
      'created_at',
      'updated_at',
    ],
    backup: true,
    restoreOrder: 230,
  },
  {
    name: 'continuation_settings',
    columns: [
      'project_id',
      'active_source_id',
      'boundary_source_id',
      'boundary_chapter_id',
      'boundary_char_offset_global',
      'boundary_mode',
      'import_completed',
      'analysis_status',
      'created_at',
      'updated_at',
    ],
    backup: true,
    restoreOrder: 240,
  },
  {
    name: 'continuation_import_jobs',
    columns: [
      'id',
      'project_id',
      'source_id',
      'source_version',
      'state',
      'stage',
      'progress_current',
      'progress_total',
      'parser_version',
      'normalization_version',
      'input_copy_relative_path',
      'checkpoint_json',
      'error_code',
      'error_message',
      'started_at',
      'updated_at',
      'completed_at',
    ],
    indexes: ['idx_continuation_import_one_active'],
    // Spec §9.6 / §15: import jobs are resumable runtime state, never backed
    // up. The first backup:false table in the manifest.
    backup: false,
    restoreOrder: 250,
  },
];
