export interface TableManifest {
  name: string;
  columns: readonly string[];
  indexes?: readonly string[];
  backup: boolean;
  restoreOrder: number;
}

/**
 * The current schema contract used by runtime validation and backup planning.
 * Keep this list aligned with the latest fresh-install CREATE TABLE statements
 * and add a migration before changing a persisted column requirement.
 */
export const SCHEMA_MANIFEST: readonly TableManifest[] = [
  {
    name: 'projects',
    columns: ['id', 'name', 'mode', 'created_at', 'updated_at'],
    backup: true,
    restoreOrder: 10,
  },
  {
    name: 'chapters',
    columns: [
      'id',
      'project_id',
      'position',
      'title',
      'synopsis',
      'content',
      'status',
      'summary_json',
      'memory_summary',
      'memory_summary_tokens',
      'finalized_at',
      'created_at',
      'updated_at',
    ],
    backup: true,
    restoreOrder: 20,
  },
  {
    name: 'fragments',
    columns: ['id', 'project_id', 'position', 'type', 'content', 'created_at'],
    backup: true,
    restoreOrder: 30,
  },
  {
    name: 'project_story_memory',
    columns: [
      'project_id', 'schema_version', 'through_chapter_id',
      'through_chapter_position', 'memory_json', 'estimated_tokens',
      'state_fingerprint', 'last_applied_patch_id', 'status', 'source',
      'dirty_from_position', 'last_error', 'updated_at',
    ],
    indexes: ['idx_project_story_memory_status', 'idx_project_story_memory_dirty'],
    backup: true,
    restoreOrder: 35,
  },
  {
    name: 'chapter_memory_patches',
    columns: [
      'chapter_id', 'project_id', 'chapter_position', 'patch_id',
      'schema_version', 'source_fingerprint', 'base_memory_fingerprint',
      'result_memory_fingerprint', 'episodic_summary_json', 'patch_json',
      'estimated_tokens', 'status', 'last_error', 'generated_at', 'applied_at',
    ],
    indexes: [
      'idx_chapter_memory_patches_project_position',
      'idx_chapter_memory_patches_status',
    ],
    backup: true,
    restoreOrder: 36,
  },
  {
    name: 'story_memory_snapshots',
    columns: [
      'id', 'project_id', 'through_chapter_id', 'through_chapter_position',
      'memory_json', 'estimated_tokens', 'state_fingerprint', 'created_at',
    ],
    indexes: ['idx_story_memory_snapshots_project_position'],
    backup: true,
    restoreOrder: 37,
  },
  {
    name: 'project_story_memory_policy',
    columns: [
      'project_id', 'mode', 'interval_chapters', 'pending_token_soft_limit',
      'update_on_key_chapter', 'updated_at',
    ],
    backup: true,
    restoreOrder: 38,
  },
  {
    name: 'story_memory_batches',
    columns: [
      'batch_id', 'project_id', 'from_chapter_id', 'from_position',
      'through_chapter_id', 'through_position', 'schema_version',
      'source_fingerprint', 'base_state_fingerprint', 'result_state_fingerprint',
      'patch_json', 'chapter_summaries_json', 'estimated_tokens', 'status',
      'last_error', 'generated_at', 'applied_at',
    ],
    indexes: [
      'idx_story_memory_batches_project_range',
      'idx_story_memory_batches_project_through',
      'idx_story_memory_batches_status',
    ],
    backup: true,
    restoreOrder: 39,
  },
  {
    name: 'plotlines',
    columns: ['id', 'project_id', 'name', 'description', 'color'],
    backup: true,
    restoreOrder: 40,
  },
  {
    name: 'project_plotlines',
    columns: ['chapter_id', 'plotline_id'],
    backup: true,
    restoreOrder: 50,
  },
  {
    name: 'characters',
    columns: [
      'id',
      'project_id',
      'collection_id',
      'name',
      'source_type',
      'data_json',
      'max_tokens',
      'estimated_tokens',
      'created_at',
    ],
    backup: true,
    restoreOrder: 60,
  },
  {
    name: 'character_collections',
    columns: [
      'id',
      'project_id',
      'name',
      'enabled',
      'max_tokens',
      'estimated_tokens',
      'created_at',
    ],
    backup: true,
    restoreOrder: 65,
  },
  {
    name: 'worldbook_collections',
    columns: [
      'id',
      'project_id',
      'name',
      'enabled',
      'max_tokens',
      'estimated_tokens',
      'created_at',
    ],
    backup: true,
    restoreOrder: 70,
  },
  {
    name: 'worldbook_entries',
    columns: [
      'id',
      'project_id',
      'collection_id',
      'keyword_primary',
      'keyword_secondary',
      'content',
      'comment',
      'enabled',
      'constant',
      'max_tokens',
      'estimated_tokens',
      'position',
      'created_at',
    ],
    backup: true,
    restoreOrder: 80,
  },
  {
    name: 'note_collections',
    columns: [
      'id',
      'project_id',
      'name',
      'enabled',
      'max_tokens',
      'estimated_tokens',
      'created_at',
    ],
    backup: true,
    restoreOrder: 85,
  },
  {
    name: 'notes',
    columns: [
      'id',
      'project_id',
      'collection_id',
      'title',
      'content',
      'max_tokens',
      'estimated_tokens',
      'created_at',
      'updated_at',
    ],
    indexes: ['idx_notes_collection_id'],
    backup: true,
    restoreOrder: 90,
  },
  {
    name: 'presets',
    columns: [
      'id',
      'project_id',
      'name',
      'is_default',
      'system_prompt',
      'writing_style',
      'temperature',
      'top_p',
      'max_tokens',
      'extra_instructions',
    ],
    backup: true,
    restoreOrder: 100,
  },
  {
    name: 'llm_config',
    columns: [
      'id',
      'name',
      'base_url',
      'api_key',
      'model_name',
      'is_active',
      'provider_type',
      'context_window',
      'max_output_tokens',
    ],
    backup: true,
    restoreOrder: 110,
  },
  {
    name: 'settings',
    columns: ['key', 'value'],
    backup: true,
    restoreOrder: 120,
  },
  {
    name: 'project_resources',
    columns: ['project_id', 'resource_type', 'resource_id', 'enabled'],
    backup: true,
    restoreOrder: 130,
  },
  {
    name: 'project_collection_settings',
    columns: ['project_id', 'resource_type', 'collection_id', 'enabled'],
    indexes: ['idx_project_collection_settings_lookup'],
    backup: true,
    restoreOrder: 135,
  },
  {
    name: 'llm_usage_logs',
    columns: [
      'id',
      'scenario',
      'input_tokens',
      'output_tokens',
      'total_tokens',
      'status',
      'error_code',
      'model_name',
      'project_id',
      'llm_config_id',
      'llm_config_name',
      'created_at',
    ],
    indexes: ['idx_llm_usage_logs_month', 'idx_llm_usage_logs_config'],
    backup: true,
    restoreOrder: 140,
  },
  {
    name: 'pipeline_tasks',
    columns: [
      'id',
      'target_type',
      'target_id',
      'status',
      'stage_results',
      'final_text',
      'error',
      'created_at',
      'updated_at',
      'resolved_at',
      'resolved_action',
    ],
    backup: true,
    restoreOrder: 150,
  },
  {
    name: 'freeform_documents',
    columns: ['project_id', 'content', 'updated_at'],
    backup: true,
    restoreOrder: 160,
  },
  {
    name: 'content_revisions',
    columns: [
      'id',
      'project_id',
      'target_type',
      'target_id',
      'title',
      'content',
      'source',
      'source_ref',
      'created_at',
    ],
    indexes: ['idx_content_revisions_target'],
    backup: true,
    restoreOrder: 170,
  },
  {
    name: 'generation_drafts',
    columns: [
      'id',
      'project_id',
      'target_type',
      'target_id',
      'content',
      'source',
      'pipeline_task_id',
      'token_count',
      'created_at',
    ],
    indexes: ['idx_generation_drafts_target'],
    backup: true,
    restoreOrder: 180,
  },
  {
    name: 'project_note_config',
    columns: [
      'project_id',
      'mode',
      'style_weights',
      'retrieval_top_k',
      'retrieval_fragment_chars',
      'enabled_note_ids',
      'updated_at',
    ],
    backup: true,
    restoreOrder: 190,
  },
  {
    name: 'note_style_profiles',
    columns: [
      'note_id',
      'profile_text',
      'profile_json',
      'analyzed_at',
      'source_hash',
    ],
    backup: true,
    restoreOrder: 200,
  },
  // Schema 19 (continuation Phase 1). Restore order is parent-first so foreign
  // keys resolve during INSERT: sources → chunks/chapters → settings. Import
  // jobs are transient runtime state and excluded from backup (Spec §9.6, §15)
  // but still listed so the schema validator recognises the tables.
  {
    name: 'continuation_sources',
    columns: [
      'id',
      'project_id',
      'version',
      'status',
      'display_name',
      'original_file_name',
      'mime_type',
      'detected_encoding',
      'file_size_bytes',
      'raw_sha256',
      'normalized_sha256',
      'normalized_char_count',
      'normalized_byte_count',
      'chapter_count',
      'parser_version',
      'normalization_version',
      'error_code',
      'error_message',
      'created_at',
      'updated_at',
      'activated_at',
    ],
    indexes: ['idx_continuation_sources_one_ready'],
    backup: true,
    restoreOrder: 210,
  },
  {
    name: 'continuation_source_text_chunks',
    columns: [
      'id',
      'source_id',
      'chunk_index',
      'char_start_offset',
      'char_end_offset',
      'content',
      'content_sha256',
    ],
    indexes: ['idx_continuation_text_chunks_range'],
    backup: true,
    restoreOrder: 220,
  },
  {
    name: 'continuation_source_chapters',
    columns: [
      'id',
      'source_id',
      'position',
      'volume_title',
      'detected_title',
      'title',
      'content_sha256',
      'char_count',
      'paragraph_count',
      'source_start_offset',
      'content_start_offset',
      'source_end_offset',
      'is_excluded',
      'exclusion_reason',
      'created_at',
      'updated_at',
    ],
    backup: true,
    restoreOrder: 230,
  },
  {
    name: 'continuation_settings',
    columns: [
      'project_id',
      'active_source_id',
      'boundary_source_id',
      'boundary_chapter_id',
      'boundary_char_offset_global',
      'boundary_mode',
      'import_completed',
      'analysis_status',
      'active_canon_snapshot_id',
      'active_style_profile_id',
      'created_at',
      'updated_at',
    ],
    backup: true,
    // Active Canon/style pointers are restored in a second phase after all
    // parent rows exist. Keep settings after the style table so delete order
    // clears this pointer-bearing row before deleting its parents.
    restoreOrder: 520,
  },
  {
    name: 'continuation_import_jobs',
    columns: [
      'id',
      'project_id',
      'source_id',
      'source_version',
      'state',
      'stage',
      'progress_current',
      'progress_total',
      'parser_version',
      'normalization_version',
      'input_copy_relative_path',
      'checkpoint_json',
      'error_code',
      'error_message',
      'started_at',
      'updated_at',
      'completed_at',
    ],
    indexes: ['idx_continuation_import_one_active'],
    // Spec §9.6 / §15: import jobs are resumable runtime state, never backed
    // up. The first backup:false table in the manifest.
    backup: false,
    restoreOrder: 250,
  },
  // Schema 20 (continuation Phase 2 Canon). Parent-first restore order so FKs
  // resolve: snapshots → runs/batches → evidence → characters → dependents.
  {
    name: 'continuation_canon_snapshots',
    columns: [
      'id',
      'project_id',
      'source_id',
      'analysis_run_id',
      'source_version',
      'source_sha256',
      'parser_version',
      'normalization_version',
      'boundary_chapter_id',
      'boundary_position',
      'boundary_char_offset_exclusive',
      'extraction_version',
      'profile',
      'revision',
      'status',
      'capabilities_json',
      'coverage_json',
      'created_at',
      'updated_at',
      'activated_at',
    ],
    indexes: ['idx_canon_snapshots_one_ready', 'idx_canon_snapshots_source'],
    backup: true,
    restoreOrder: 260,
  },
  {
    name: 'continuation_analysis_runs',
    columns: [
      'id',
      'project_id',
      'source_id',
      'source_version',
      'source_sha256',
      'parser_version',
      'normalization_version',
      'boundary_chapter_id',
      'boundary_position',
      'boundary_char_offset_exclusive',
      'canon_snapshot_id',
      'profile',
      'model_config_id',
      'state',
      'stage',
      'progress_current',
      'progress_total',
      'extraction_version',
      'checkpoint_json',
      'error_code',
      'error_message',
      'created_at',
      'updated_at',
      'completed_at',
    ],
    indexes: ['idx_analysis_runs_project_state'],
    backup: true,
    restoreOrder: 270,
  },
  {
    name: 'continuation_analysis_batches',
    columns: [
      'run_id',
      'canon_snapshot_id',
      'batch_index',
      'start_position',
      'end_position',
      'input_hash',
      'idempotency_key',
      'state',
      'attempt_count',
      'result_json',
      'error_code',
      'error_message',
      'created_at',
      'updated_at',
      'completed_at',
    ],
    indexes: ['idx_continuation_analysis_batches_state'],
    backup: true,
    restoreOrder: 280,
  },
  {
    name: 'continuation_analysis_work_items',
    columns: [
      'run_id',
      'batch_index',
      'material_type',
      'state',
      'attempt_count',
      'result_json',
      'error_code',
      'error_message',
      'created_at',
      'updated_at',
      'completed_at',
    ],
    indexes: ['idx_continuation_analysis_work_items_state'],
    backup: true,
    restoreOrder: 285,
  },
  // Schema 24: historical memory is intentionally separate from Canon facts
  // and evidence. It is backed up with its source fingerprint so restore can
  // safely invalidate it when the source/boundary changes.
  {
    name: 'continuation_historical_digests',
    columns: [
      'id',
      'project_id',
      'source_id',
      'source_version',
      'source_sha256',
      'parser_version',
      'normalization_version',
      'boundary_chapter_id',
      'boundary_position',
      'boundary_char_offset_exclusive',
      'start_position',
      'end_position',
      'status',
      'summary',
      'keywords_json',
      'model_config_id',
      'error_code',
      'error_message',
      'created_at',
      'updated_at',
      'completed_at',
    ],
    indexes: ['idx_historical_digests_lookup'],
    backup: true,
    restoreOrder: 286,
  },
  {
    name: 'continuation_historical_digest_chapters',
    columns: ['digest_id', 'chapter_id', 'chapter_position', 'chapter_title'],
    indexes: ['idx_historical_digest_chapters_position'],
    backup: true,
    restoreOrder: 287,
  },
  {
    name: 'continuation_historical_index_terms',
    columns: [
      'digest_id',
      'chapter_id',
      'chapter_position',
      'term_normalized',
      'term_display',
      'term_kind',
    ],
    indexes: ['idx_historical_index_terms_lookup'],
    backup: true,
    restoreOrder: 288,
  },
  {
    name: 'canon_evidence',
    columns: [
      'id',
      'project_id',
      'source_id',
      'snapshot_id',
      'chapter_id',
      'chapter_position',
      'paragraph_start',
      'paragraph_end',
      'char_start',
      'char_end',
      'quote_preview',
      'quote_sha256',
      'analysis_run_id',
      'created_at',
    ],
    indexes: ['idx_canon_evidence_range'],
    backup: true,
    restoreOrder: 290,
  },
  {
    name: 'canon_evidence_links',
    columns: [
      'evidence_id',
      'snapshot_id',
      'owner_type',
      'owner_id',
      'created_at',
    ],
    indexes: ['idx_canon_evidence_links_owner'],
    backup: true,
    restoreOrder: 300,
  },
  {
    name: 'canon_world_rules',
    columns: [
      'id',
      'project_id',
      'source_id',
      'snapshot_id',
      'analysis_run_id',
      'valid_from_position',
      'valid_to_position',
      'first_observed_position',
      'last_observed_position',
      'confidence',
      'review_status',
      'origin',
      'extraction_version',
      'revision',
      'supersedes_id',
      'user_reviewed_at',
      'created_at',
      'updated_at',
      'category',
      'title',
      'description',
      'constraint_level',
    ],
    indexes: [
      'idx_canon_world_rules_snapshot_review',
      'idx_canon_world_rules_snapshot_from',
      'idx_canon_world_rules_category',
    ],
    backup: true,
    restoreOrder: 310,
  },
  {
    name: 'canon_characters',
    columns: [
      'id',
      'project_id',
      'source_id',
      'snapshot_id',
      'analysis_run_id',
      'valid_from_position',
      'valid_to_position',
      'first_observed_position',
      'last_observed_position',
      'confidence',
      'review_status',
      'origin',
      'extraction_version',
      'revision',
      'supersedes_id',
      'user_reviewed_at',
      'created_at',
      'updated_at',
      'canonical_name',
      'description',
      'background',
      'appearance_json',
      'personality_json',
      'values_json',
      'behavior_patterns_json',
      'speech_style_json',
      'abilities_json',
      'weaknesses_json',
      'goals_json',
      'fears_json',
      'secrets_json',
      'first_appearance_position',
      'importance',
    ],
    indexes: [
      'idx_canon_characters_snapshot_review',
      'idx_canon_characters_snapshot_from',
      'idx_canon_characters_name',
    ],
    backup: true,
    restoreOrder: 320,
  },
  {
    name: 'canon_character_aliases',
    columns: [
      'id',
      'project_id',
      'source_id',
      'snapshot_id',
      'analysis_run_id',
      'valid_from_position',
      'valid_to_position',
      'first_observed_position',
      'last_observed_position',
      'confidence',
      'review_status',
      'origin',
      'extraction_version',
      'revision',
      'supersedes_id',
      'user_reviewed_at',
      'created_at',
      'updated_at',
      'character_id',
      'alias',
      'alias_normalized',
      'alias_type',
      'is_ambiguous',
    ],
    indexes: [
      'idx_canon_character_aliases_snapshot_review',
      'idx_canon_character_aliases_snapshot_from',
      'idx_canon_aliases_norm',
      'idx_canon_aliases_char',
    ],
    backup: true,
    restoreOrder: 330,
  },
  {
    name: 'canon_character_state_snapshots',
    columns: [
      'id',
      'project_id',
      'source_id',
      'snapshot_id',
      'analysis_run_id',
      'valid_from_position',
      'valid_to_position',
      'first_observed_position',
      'last_observed_position',
      'confidence',
      'review_status',
      'origin',
      'extraction_version',
      'revision',
      'supersedes_id',
      'user_reviewed_at',
      'created_at',
      'updated_at',
      'character_id',
      'chapter_position',
      'location',
      'physical_state',
      'emotional_state',
      'identity_state',
      'organization_state',
      'current_goal',
      'possessions_json',
      'abilities_state_json',
      'alive_state',
      'summary',
    ],
    indexes: [
      'idx_canon_character_state_snapshots_snapshot_review',
      'idx_canon_character_state_snapshots_snapshot_from',
      'idx_canon_char_state_pos',
    ],
    backup: true,
    restoreOrder: 340,
  },
  {
    name: 'canon_relationships',
    columns: [
      'id',
      'project_id',
      'source_id',
      'snapshot_id',
      'analysis_run_id',
      'valid_from_position',
      'valid_to_position',
      'first_observed_position',
      'last_observed_position',
      'confidence',
      'review_status',
      'origin',
      'extraction_version',
      'revision',
      'supersedes_id',
      'user_reviewed_at',
      'created_at',
      'updated_at',
      'source_character_id',
      'target_character_id',
      'relation_type',
      'attitude',
      'public_status',
      'description',
      'causes_json',
    ],
    indexes: [
      'idx_canon_relationships_snapshot_review',
      'idx_canon_relationships_snapshot_from',
      'idx_canon_rel_pair',
    ],
    backup: true,
    restoreOrder: 350,
  },
  {
    name: 'canon_plot_threads',
    columns: [
      'id',
      'project_id',
      'source_id',
      'snapshot_id',
      'analysis_run_id',
      'valid_from_position',
      'valid_to_position',
      'first_observed_position',
      'last_observed_position',
      'confidence',
      'review_status',
      'origin',
      'extraction_version',
      'revision',
      'supersedes_id',
      'user_reviewed_at',
      'created_at',
      'updated_at',
      'title',
      'description',
      'level',
      'status',
      'importance',
      'start_position',
      'last_advanced_position',
      'resolved_position',
      'established_facts_json',
      'unresolved_questions_json',
      'expected_directions_json',
    ],
    indexes: [
      'idx_canon_plot_threads_snapshot_review',
      'idx_canon_plot_threads_snapshot_from',
      'idx_canon_plot_status',
    ],
    backup: true,
    restoreOrder: 360,
  },
  {
    name: 'canon_plot_thread_characters',
    columns: [
      'snapshot_id',
      'plot_thread_id',
      'character_id',
      'role',
      'created_at',
    ],
    backup: true,
    restoreOrder: 370,
  },
  {
    name: 'canon_character_experiences',
    columns: [
      'id',
      'project_id',
      'source_id',
      'snapshot_id',
      'analysis_run_id',
      'valid_from_position',
      'valid_to_position',
      'first_observed_position',
      'last_observed_position',
      'confidence',
      'review_status',
      'origin',
      'extraction_version',
      'revision',
      'supersedes_id',
      'user_reviewed_at',
      'created_at',
      'updated_at',
      'character_id',
      'chapter_position',
      'event_type',
      'title',
      'description',
      'involved_character_ids_json',
      'impact_on_personality',
      'impact_on_goal',
      'impact_on_relationship',
      'knowledge_gained_json',
      'secrets_learned_json',
      'importance',
    ],
    indexes: [
      'idx_canon_character_experiences_snapshot_review',
      'idx_canon_character_experiences_snapshot_from',
      'idx_canon_exp_char_pos',
    ],
    backup: true,
    restoreOrder: 380,
  },
  {
    name: 'canon_character_knowledge',
    columns: [
      'id',
      'project_id',
      'source_id',
      'snapshot_id',
      'analysis_run_id',
      'valid_from_position',
      'valid_to_position',
      'first_observed_position',
      'last_observed_position',
      'confidence',
      'review_status',
      'origin',
      'extraction_version',
      'revision',
      'supersedes_id',
      'user_reviewed_at',
      'created_at',
      'updated_at',
      'character_id',
      'fact_key',
      'fact_summary',
      'knowledge_state',
      'learned_position',
      'learned_from_character_id',
      'misunderstanding_summary',
    ],
    indexes: [
      'idx_canon_character_knowledge_snapshot_review',
      'idx_canon_character_knowledge_snapshot_from',
      'idx_canon_know_char_pos',
    ],
    backup: true,
    restoreOrder: 390,
  },
  {
    name: 'canon_timeline_events',
    columns: [
      'id',
      'project_id',
      'source_id',
      'snapshot_id',
      'analysis_run_id',
      'valid_from_position',
      'valid_to_position',
      'first_observed_position',
      'last_observed_position',
      'confidence',
      'review_status',
      'origin',
      'extraction_version',
      'revision',
      'supersedes_id',
      'user_reviewed_at',
      'created_at',
      'updated_at',
      'event_key',
      'title',
      'summary',
      'event_type',
      'chapter_position',
      'char_start',
      'char_end',
      'participant_character_ids_json',
      'location_before',
      'location_after',
      'relative_time_json',
      'causes_event_ids_json',
      'consequences_event_ids_json',
      'importance',
    ],
    indexes: [
      'idx_canon_timeline_events_snapshot_review',
      'idx_canon_timeline_events_snapshot_from',
      'idx_canon_timeline_pos',
    ],
    backup: true,
    restoreOrder: 400,
  },
  // Schema 21 (continuation Phase 3). Parent-first: settings → runs →
  // artifacts/plans/checks → proposals → entities/events → outbox/style.
  {
    name: 'continuation_generation_settings',
    columns: [
      'project_id',
      'strictness_profile',
      'world_rule_level',
      'character_level',
      'relationship_level',
      'plot_level',
      'experience_level',
      'knowledge_level',
      'style_level',
      'allow_new_characters',
      'allow_new_locations',
      'allow_new_organizations',
      'major_relationship_change_policy',
      'major_power_change_policy',
      'character_death_policy',
      'resurrection_policy',
      'planner_llm_config_id',
      'writer_llm_config_id',
      'checker_llm_config_id',
      'repair_llm_config_id',
      'state_extraction_llm_config_id',
      'planner_confirmation_policy',
      'checker_enabled',
      'max_repair_rounds',
      'target_chapter_chars',
      'custom_rules_json',
      'created_at',
      'updated_at',
    ],
    backup: true,
    restoreOrder: 410,
  },
  {
    name: 'continuation_generation_runs',
    columns: [
      'id',
      'project_id',
      'chapter_id',
      'target_position',
      'source_id',
      'source_snapshot_json',
      'canon_snapshot_id',
      'canon_revision',
      'story_memory_fingerprint',
      'story_memory_through_position',
      'input_revision_hash',
      'user_instruction',
      'settings_snapshot_json',
      'context_snapshot_json',
      'context_trace_json',
      'token_usage_json',
      'state',
      'stage',
      'completion_reason',
      'adopted_revision_hash',
      'finalized_revision_hash',
      'error_code',
      'error_message',
      'created_at',
      'updated_at',
      'completed_at',
    ],
    indexes: [
      'idx_continuation_runs_project_created',
      'idx_continuation_runs_chapter_created',
      'idx_continuation_runs_state',
    ],
    backup: true,
    restoreOrder: 420,
  },
  {
    name: 'continuation_generation_artifacts',
    columns: [
      'id',
      'run_id',
      'stage',
      'repair_round',
      'parent_artifact_id',
      'content',
      'content_hash',
      'created_at',
    ],
    indexes: ['idx_continuation_artifacts_run_created'],
    backup: true,
    restoreOrder: 430,
  },
  {
    name: 'continuation_plans',
    columns: [
      'run_id',
      'schema_version',
      'plan_json',
      'plan_hash',
      'confirmation_status',
      'confirmed_at',
      'created_at',
    ],
    backup: true,
    restoreOrder: 440,
  },
  {
    name: 'continuation_check_results',
    columns: [
      'id',
      'run_id',
      'chapter_id',
      'artifact_id',
      'artifact_hash',
      'category',
      'subtype',
      'severity',
      'confidence',
      'generated_start',
      'generated_end',
      'generated_excerpt',
      'description',
      'entity_ref_type',
      'entity_ref_id',
      'evidence_ids_json',
      'suggested_fix',
      'resolution_status',
      'created_at',
      'updated_at',
    ],
    indexes: ['idx_continuation_checks_run_artifact'],
    backup: true,
    restoreOrder: 450,
  },
  {
    name: 'continuation_state_proposals',
    columns: [
      'id',
      'project_id',
      'chapter_id',
      'source_run_id',
      'extraction_content_hash',
      'chapter_revision_hash',
      'proposal_type',
      'subject_ref_type',
      'subject_ref_id',
      'payload_json',
      'proposal_fingerprint',
      'evidence_start',
      'evidence_end',
      'status',
      'decision_note',
      'decided_at',
      'created_at',
      'updated_at',
    ],
    indexes: ['idx_continuation_proposals_project_status'],
    backup: true,
    restoreOrder: 460,
  },
  {
    name: 'continuation_entities',
    columns: [
      'id',
      'project_id',
      'entity_type',
      'canonical_name',
      'profile_json',
      'created_from_proposal_id',
      'status',
      'created_at',
      'updated_at',
    ],
    backup: true,
    restoreOrder: 470,
  },
  {
    name: 'continuation_entity_aliases',
    columns: [
      'entity_id',
      'normalized_alias',
      'display_alias',
      'created_at',
    ],
    backup: true,
    restoreOrder: 480,
  },
  {
    name: 'continuation_state_events',
    columns: [
      'id',
      'proposal_id',
      'project_id',
      'chapter_id',
      'chapter_position',
      'chapter_revision_hash',
      'event_type',
      'entity_refs_json',
      'payload_json',
      'valid_from_position',
      'valid_to_position',
      'created_at',
      'invalidated_at',
      'invalidation_reason',
    ],
    indexes: [
      'idx_continuation_events_project_position',
      'idx_continuation_events_chapter',
    ],
    backup: true,
    restoreOrder: 490,
  },
  {
    name: 'continuation_state_sync_outbox',
    columns: [
      'id',
      'project_id',
      'chapter_id',
      'operation',
      'payload_json',
      'dedupe_key',
      'state',
      'attempt_count',
      'last_error',
      'created_at',
      'updated_at',
      'completed_at',
    ],
    indexes: ['idx_continuation_outbox_state'],
    backup: true,
    restoreOrder: 500,
  },
  {
    name: 'continuation_style_profiles',
    columns: [
      'id',
      'project_id',
      'source_id',
      'source_version',
      'source_sha256',
      'parser_version',
      'normalization_version',
      'boundary_chapter_id',
      'boundary_position',
      'boundary_char_offset_exclusive',
      'analysis_run_id',
      'canon_snapshot_id',
      'profile_schema_version',
      'analyzer_version',
      'profile_json',
      'metrics_json',
      'sample_refs_json',
      'user_overrides_json',
      'profile_hash',
      'confidence',
      'state',
      'review_status',
      'error_code',
      'error_message',
      'created_at',
      'updated_at',
      'completed_at',
    ],
    indexes: [
      'idx_continuation_style_profiles_project_state',
      'idx_continuation_style_profiles_fingerprint',
    ],
    backup: true,
    restoreOrder: 510,
  },
  {
    name: 'continuation_resource_bindings',
    columns: [
      'id',
      'project_id',
      'resource_kind',
      'resource_id',
      'continuation_usage',
      'enabled_for_continuation',
      'sort_order',
      'created_at',
      'updated_at',
    ],
    indexes: [
      'idx_continuation_resource_bindings_project_usage',
      'idx_continuation_resource_bindings_one_preset',
    ],
    backup: true,
    restoreOrder: 515,
  },
];
